### ISSUE TITLE
Mysterious codegen errors when trying to render map in changelist

### ISSUE THREAD

**Issue by oliver-daniel** [vb64/django.admin.geomap#33] opened 2023-01-19 00:56 UTC
Hello!

I'm trying to implement this app in my own project, to give my admin users a satisfying overview of all the location-based entities we maintain in our database.

I will also lead with the fact that I am using the `GeoItem` class in what may be a non-standard way, attaching it to an entity with a one-to-one key to a separate Location model (as I wish to see the map in admin pages for the prior entity).

The map renders like a charm in the individual change form for each entity, but I receive some strange errors in my client that seem to indicate that the JS is being generated incorrectly for the changelist-view map.

The first one I receive is `Uncaught SyntaxError: Unexpected token ')' (at (index):993:15)`, and clicking through I see the following:

![image](https://user-images.githubusercontent.com/17235417/213329675-8d5604d5-5c51-4198-aebf-4730c0e2d4f1.png)

This seems to indicate to me that the recommended default value of the `geomap_latitude`/`longitude` properties (i.e., `''`) is appearing directly in this generated code. Changing this to other values like `test` or `NaN` seem to confirm this, but somehow the issue appears elsewhere (potentially in entities with no/null location).

The second error is `Uncaught TypeError: map.addOverlay is not a function at (index):14861:5`, to which I have no answer. I don't know whether it's correlated to the first one or not.

I see that this project is still in active developent; if possible, I would love to hop on a call with a developer and figure out the issue, and I would be happy to follow up this issue with detailed comments explaining what happened, for anyone else who might encounter these problems in the future.

Thank you, and please let me know if I can supply any more information.

**Comment by vb64** [comment] 2023-01-19 07:33
> This seems to indicate to me that the recommended default value of the `geomap_latitude`/`longitude` properties (i.e., `''`) is appearing directly in this generated code. Changing this to other values like `test` or `NaN` seem to confirm this, but somehow the issue appears elsewhere (potentially in entities with no/null location).

Thanks for your bug report, a fix for the case of an objects with missing coordinates will be released.

For a quick fix, you can add a filter to remove such objects from the changelist in the Django admin.

The implementation of the geomap_latitude / longitude properties given in the readme is just an example. You can implement any logic there according to the scheme of your models.

**Comment by vb64** [comment] 2023-01-19 07:37
> The second error is `Uncaught TypeError: map.addOverlay is not a function at (index):14861:5`, to which I have no answer. I don't know whether it's correlated to the first one or not.
> 
> I see that this project is still in active developent; if possible, I would love to hop on a call with a developer and figure out the issue, and I would be happy to follow up this issue with detailed comments explaining what happened, for anyone else who might encounter these problems in the future.
> 
> Thank you, and please let me know if I can supply any more information.

For this error, it is better to create a separate issue and provide additional information, as suggest [CONTRIBUTING.md](https://github.com/vb64/django.admin.geomap/blob/main/CONTRIBUTING.md#write-bug-reports-with-detail-background-and-sample-code)

**Comment by vb64** [comment] 2023-01-23 06:22
> This seems to indicate to me that the recommended default value of the `geomap_latitude`/`longitude` properties (i.e., `''`) is appearing directly in this generated code.

New in version 1.5

If at least one of geomap_longitude/geomap_latitude properties returns an empty string, then the corresponding object will not be displayed on the map. For example, objects that do not have coordinates or some kind of "secret" objects from your database.

Please update your project to version 1.5 of the library and and check for error in context of your project.

Please post your results here.

**Comment by oliver-daniel** [comment] 2023-01-23 18:56
Hi Vitaly, thanks so much for the quick turnaround. I'm thrilled to say that, with a little extra finagling on my models (in particular the two properties), I was able to get the map to render in my changelist, and to respond to changes in the queryset filter via the URL params. Now to get to playing with all the other options. :)

Thank you!

**Comment by vb64** [comment] 2023-01-24 06:38
> Now to get to playing with all the other options. :)

Good luck, and write here about the problems that you will meet. It is advisable for each problem to create a separate issue and follow the recommendations from [CONTRIBUTING.md](https://github.com/vb64/django.admin.geomap/blob/main/CONTRIBUTING.md)

Can I consider the problems described in this issue solved in the version of the library 1.5 and close this topic?

**Comment by vb64** [comment] 2023-02-07 07:21
Let's assume the problem is solved.

**Closed by vb64** 2023-02-07 07:21 UTC
